[Unit]
Description=Nixcabot Bot
After=network.target

[Service]
Type=simple
User=botuser
WorkingDirectory=/opt/nixcabot
Environment="BOT_TOKEN=${BOT_TOKEN}"
Environment="OWNER_ID=${OWNER_ID}"
Environment="GROUP_CHAT_ID=${GROUP_CHAT_ID}"
Environment="DEXSCREENER_API_KEY=${DEXSCREENER_API_KEY}"
ExecStart=/usr/bin/python3 bot.py
Restart=always

[Install]
WantedBy=multi-user.target
